version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres-db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

    secrets:
      - postgres_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - full-stack-spring-boot-react

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: spring-backend
    restart: always

    ports:
      - "8080:8080"

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}

    secrets:
      - postgres_password

    networks:
      - full-stack-spring-boot-react

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile

    container_name: react-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

    networks:
      - full-stack-spring-boot-react

volumes:
  postgres_data:

networks:
  full-stack-spring-boot-react:
    driver: bridge

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt